### ISSUE TITLE
Allow scenarioId as a parameter

### ISSUE THREAD

**Issue by lirudayam** [SAP/ai-sdk-js#217]
### Describe the Problem

It is an issue for some projects where scenarioId is by default orchestration. 

### Propose a Solution

It would be great if this could be a parameter, additionally to the AI resource group

### Affected Development Phase

Development

### Impact

Inconvenience

**Comment by MatKuhr** [comment]
Hi @lirudayam, for Orchestration the AI SDK has a dedicated convenience API. Please take a look here: https://www.npmjs.com/package/@sap-ai-sdk/orchestration

If this does not cover what you need, please explain your use case in more detail and what is missing from the orchestration client.

**Comment by lirudayam** [comment]
Hi @MatKuhr 
So maybe I'm just not getting the idea, but if I use @sap-ai-sdk/ai-api I can trigger by deployments (if needed) of LLMs under a specific resource group, the scenarioId "foundation-models" and with the respective executableId. So I can get a deployment URL back which I can use for inference, either via SDK or via axios call. When I want to know use the sap-ai-sdk/orchestration, the code contains the scenarioId "orchestration", however within this scenario I don't have any deployments isn't it? I get this error then:

 GET /v2/lm/deployments?scenarioId=orchestration&status=RUNNING
Error loading OrchestrationClient: Error: No deployment matched the given criteria: {"scenarioId":"orchestration","resourceGroup":"<resourceGroup>"}
    at resolveDeploymentId node_modules/@sap-ai-sdk/ai-api/src/utils/deployment-resolver.ts:129:11)

Is there something wrong with my thinking or is there another idea behind it?

**Comment by MatKuhr** [comment]
Correct, you have to first create such a deployment for orchestration as well. Please follow the instructions [here](https://help.sap.com/docs/sap-ai-core/sap-ai-core-service-guide/create-deployment-for-orchestration).
