### ISSUE TITLE
ERROR on server start: ❗️ TypeError: Unknown file extension ".ts" when using sample-cap & sample-code

### ISSUE THREAD

**Issue by jacobahtan** [SAP/ai-sdk-js#233]
### Describe the Question

i've taken reference from the sample-code/src/orchestration.ts and try to refactor/implement simply the import of library and chatcompletion, into my existing cap-ts project. 
but when i ran cds-ts watch --profile hybrid, i get the following error.
i even tried to copy the libraries into local project, but still facing this issue.
please advise.

`
api % cds-ts watch --profile hybrid
 
cds serve all --with-mocks --in-memory? --profile hybrid 
live reload enabled for browsers 
resolving cloud service bindings...
Getting service key citizen-genai-rag-destination-key
Getting service key citizen-genai-rag-hdi-container-key
Getting service key citizen-genai-rag-uaa-key
bound db to Cloud Foundry managed service citizen-genai-rag-hdi-container:citizen-genai-rag-hdi-container-key
bound destinations to Cloud Foundry managed service citizen-genai-rag-destination:citizen-genai-rag-destination-key
bound auth to Cloud Foundry managed service citizen-genai-rag-uaa:citizen-genai-rag-uaa-key

        ___________________________
 
[cds] - loading server from { file: 'srv/server.js' }
[cds] - loaded model from 5 file(s):

  srv/service.cds
  srv/rag-service.cds
  srv/notification-service.cds
  srv/manager-service.cds
  db/data-model.cds

[cds] - connect using bindings from: { registry: '~/.cds-services.json' }
[cds] - connect to db > hana {
_HIDDEN_
}

❗️ ERROR on server start: ❗️

 TypeError: Unknown file extension ".ts" for /Users/xxx/Desktop/2024/Experimental/temp-delete/02-embedding-business-context-vector-engine/cap-app/api/srv/rag-service.ts
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:176:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:219:36)
    at defaultLoad (node:internal/modules/esm/load:143:22)
    at async ModuleLoader.load (node:internal/modules/esm/loader:555:7)
    at async ModuleLoader.moduleProvider (node:internal/modules/esm/loader:434:45)
    at async link (node:internal/modules/esm/module_job:87:21) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
`

**Comment by ZhongpinWang** [comment]
Hi @jacobahtan ,

Thanks for reaching out.

Just as a first try, can you install `tsx` globally, and use `cds-tsx` instead of `cds-ts` which uses `ts-node` under the hood?

If the problem still persists, could you share your `tsconfig.json`?

**Comment by jjtang1985** [comment]
It seems this is related to CAP framework itself, instead of using Cloud SDK.
Here is the [support channel](https://cap.cloud.sap/docs/resources/#support-channels), if you want to learn more about CAP.
