### ISSUE TITLE
AI Core via Destination Service

### ISSUE THREAD

**Issue by FascinatedTV** [SAP/ai-sdk-js#245]
### Describe the Problem

Currently it is only possible to provide the aicore credentials via the `AICORE_SERVICE_KEY` environment variable
or through the `VCAP_SERVICES` of a binding to the aicore instance.
This only works if the application and the aicore instance are on the same subaccount.
When working on different subaccounts utilizing the destination service, this doesn't work anymore,
as there is no service binding to the aicore instance in the 'VCAP_SERVICES'.

### Propose a Solution

The `@sap-cloud-sdk/connectivity` package offers the `getDestinationFromDestinationService` function,
which is able to provide the same information, by giving the destination information, which could be provided by environment variables.

### Describe Alternatives

As an alternative, the same subaccount could provide an `user-provided service`.
This does not work right now, as the service-binding-label is `"user-provided" != "aicore"`

### Affected Development Phase

Development

### Impact

Inconvenience

**Comment by tomfrenken** [comment]
Hey @FascinatedTV,

to understand your setup a little better, I need a bit more information.

First of all, do you want to create multiple applications in multiple sub-accounts all using the same `aicore` service binding?
If so, the only way that is currently supported is to put the credentials from your "main" subaccount into a .env file as you've already pointed out containing the `AICORE_SERVICE_KEY`.

How are you currently trying to utilize that destination service?
Do you try to access the service through the destination service, or are you trying to access the same application from a different subaccount through the destination service?

If it is the latter, I would expect no issues, as only the central application would require the binding.
If it is the former, this wouldn't work, as you have pointed out.

Finally, am I right in assuming that your feature request is essentially to enable the use of user-provided services for the aicore service?

**Comment by FascinatedTV** [comment]
Hi @tomfrenken,

As you pointed out, I'm trying to access the same aicore instance from different subaccounts (the first case you mentioned).
This is currently only available via the .env file, thus this shouldn't be used in production settings (which is also logged by the framework).

My feature request is to enable the support of getting the [destination information](https://github.com/SAP/ai-sdk-js/blob/0aec356d019205f44f739aa86216fcf8bc4a869a/packages/core/src/context.ts#L34) through a provided destinationService Name (for example by utilising the `getDestinationFromDestinationService` function provided by `@sap-cloud-sdk/connectivity`).

This setup would enable the user in a production setting to bind the destination service to the application (e.g. in MTAs)
without manually providing the environments.

Another advantage is the option for hybrid testing in situation using for example the Cloud Application Programming Model (CAP) by also binding the destination service with `cds bind ...`

**Comment by tomfrenken** [comment]
Hi @FascinatedTV,

Alright, I've added the feature request to our backlog and discussed it already with our PO & architect, we agreed that it makes sense.

However, I can't give you a timeline yet on how fast we will implement this feature.

**Comment by FascinatedTV** [comment]
Hi @tomfrenken,
Thank you for your quick response and for the update.
Looking forward for the feature :)

**Comment by ZhongpinWang** [comment]
Hi @FascinatedTV,

Thanks again for your feature request.

We have supported this feature in all of our clients and merged it. It will be published in our next release. In the meanwhile, you can test this feature by setting the package version to `canary`.

Documentation can be found in each package's README, search "custom destination". You can also find examples in our [sample-code](https://github.com/SAP/ai-sdk-js/tree/main/sample-code#chat-completion-with-custom-destination) by checking the implementation.

**Comment by FascinatedTV** [comment]
Thank you a lot for your feedback and the implementation.

Best regards
