### ISSUE TITLE
Question about using ai-sdk-js library to run models locally

### ISSUE THREAD

**Issue by LiuXiaoKai03** [SAP/ai-sdk-js#309]
### Describe the Question

Hi all, 

I've recently been experimenting with the ai-sdk-js library, and I've run into some issues when trying to use the foundation models locally, mainly regarding the AICORE_SERVICE_KEY value. I have created an instance of the ai core service in BTP with the gpt model deployed and downloaded the service key. I guess the .env file has the following format,

`
AICORE_SERVICE_KEY="{
'clientid': 'xxx', 
'clientsecret': 'xxx', 
'url': 'xxx', 
'identityzone': 'xxx', 
'identityzoneid': 'xxx', 
'appname': 'xxx', 
'serviceurls': 
{
'AI_API_URL': 'xxxx'
}
}"
`

But the error log shows 'Error in chatCompletion: Error: Failed to fetch the list of deployments: ErrorWithCause: Could not fetch client credentials token for service of type "aicore"'.
 
I was wondering if you could provide some guidance on how to solve the problem above. 

Thank you very much.

**Comment by ZhongpinWang** [comment]
Hi @LiuXiaoKai03 ,

Thanks for opening the issue. Could you please try switching `'` and `"`? So the outside quote should be single quote and within JSON, it should be double quote.

**Comment by ZhongpinWang** [comment]
@LiuXiaoKai03 I will close this issue as switching quotes should solve the problem. If the problem still persists, feel free to reopen it.

**Comment by LiuXiaoKai03** [comment]
It didn't work. I verify that I have the right key as the model can be accessed via http request. But via sdk it reports an error.

**Comment by ZhongpinWang** [comment]
Hi @LiuXiaoKai03 , have you loaded the environment variable somehow? 

You can use `dotenv` to load `.env` file programatically, or run `node --env-file=.env --loader ts-node/esm server.ts` to feed node with the `.env` file. Or check for your framework how to load environment variables. I think our documentation is somewhat misleading, we don't by default check `.env` file but read always from `process.env`. We will update the documentation.
