### ISSUE TITLE
JSON Schema for Chat Completion

### ISSUE THREAD

**Issue by ch-sap** [SAP/ai-sdk-js#310]
### Describe the Question

Dear colleagues,

when I use method run of AzureOpenAiChatClient, I can add type:'json_object' in the response_format of AzureOpenAiCreateChatCompletionRequest. Is it possible to add a schema for the json response format?

This is a JavaScript related question.

const response = await this.chatClient.run({
      messages: [
        {
          role: 'user',
          content: `tags: ${tags}`
        },
        {
          role: 'system',
          content:
            `${GenAI.AI_PROMPT_INTRO} ${rhyme ? GenAI.AI_PROMPT_RHYME : ''} ` +
            `${GenAI.AI_PROMPT_LANGUAGE}${language}. ${GenAI.AI_PROMPT_FORMAT}`
        }
      ],
      response_format: {
        type:'json_object',
        schema: {
          "$schema": "http://json-schema.org/draft-07/schema#",
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "description": {
              "type": "string"
            }
          },
          "required": ["title", "description"]
        }
      },
      // The temperature defines how deterministic AI is (lower value more deterministic, higher value more creative).
      temperature: 0.5,
      max_tokens: 300
    });

Best regards,
Christine

**Comment by ZhongpinWang** [comment]
Hi @ch-sap ,

Thanks for raising this question. 

Currently, we are generating our client based on the Azure OpenAI spec version `2024-06-01`. Using `schema` is unfortunately not available in this stable version, but the [next stable one](https://github.com/Azure/azure-rest-api-specs/blob/cfe266748ace6a5775d0d23ecbc654741d91958b/specification/cognitiveservices/data-plane/AzureOpenAI/inference/stable/2024-10-21/inference.yaml#L977) `2024-10-21`.

Therefore, I tried to cast the `type` to `any` and give it the value `json_schema` with also `schema` property defined. One more thing we theoretically need to do is to set `apiVersion` in `CustomRequestConfig` to `2024-10-21`. 

The complete example I used to test:

```ts
    const response = await new AzureOpenAiChatClient('gpt-4o').run({
    messages: [{ role: 'user', content: 'What is the capital of France? Return me only a json object with key `country` and value `France`, and key `capital` and value the actual city. Do not include markdown syntax.' }],
    response_format: {
      type: 'json_schema' as any, // Cast to `any`
      json_schema: {
        name: 'capital-of-france',
        schema: {
          type: 'object',
          properties: {
            country: { type: 'string', const: 'France' },
            capital: { type: 'string' }
          },
          required: ['country', 'capital'],
          additionalProperties: false
        }
      }
    }
  },
  {
    params: {
      'api-version': '2024-10-21' // Use the newer API version
    }
  }
```

This could be a temporary workaround if schema has to be used now until we generate the new client based on the new spec and release it.

**Comment by ch-sap** [comment]
It worked. Thank you!
